/* FanTom — definition address-map exporter.
 *
 * Turns loaded NisROM-style XML definitions into an English-readable
 * map: for every definition, every table that lives at a real ROM
 * address, one row —
 *
 *   Address | Controls | Layout | Values mean | Category
 *
 * Built ONLY from definition data (names, descriptions, categories,
 * scaling units/expressions) — nothing invented. The same module runs
 * in the browser (Export Map button; defs come from the Defs registry)
 * and under node (tools/defmap/export-defmap.js; defs come from XML
 * files on disk).
 */
(function () {
    'use strict';

    function hex(n) {
        return '0x' + Number(n).toString(16).toUpperCase();
    }

    // scaling may be an inline object, a registry name (string), or null.
    // scalingBook: name -> {units, expression, toByte} harvested from
    // <scalingbase> elements across all definition files.
    function scalingText(scaling, scalingBook) {
        if (!scaling) return '';
        let s = scaling;
        if (typeof scaling === 'string') {
            s = (scalingBook && scalingBook[scaling]) || null;
            if (!s) return 'scaling "' + scaling + '"';
        }
        const parts = [];
        if (s.units) parts.push(s.units);
        if (s.expression && s.expression !== 'x') parts.push('value = ' + s.expression);
        else if (s.expression === 'x') parts.push('raw value');
        return parts.join(', ');
    }

    function axisText(t) {
        const bits = [];
        const ax = (a, label) => {
            if (!a) return;
            const nm = a.name || a.type || label;
            if (a.address != null) bits.push(label + ': ' + nm + ' @ ' + hex(a.address));
            else if (a.values && a.values.length) bits.push(label + ': ' + nm);
        };
        ax(t.xAxis, 'X axis');
        ax(t.yAxis, 'Y axis');
        return bits.join('; ');
    }

    function controlsText(t) {
        let s = t.name || '(unnamed table)';
        if (t.description) s += ' — ' + String(t.description).replace(/\s+/g, ' ').trim();
        return s;
    }

    function layoutText(t) {
        const nx = t.sizex || 1, ny = t.sizey || 1;
        const shape = ny > 1 ? (nx + '×' + ny) : String(nx);
        return shape + ' ' + (t.storagetype || 'uint8');
    }

    function defTitle(def) {
        const r = def.romid || {};
        const bits = [r.xmlid || '(no xmlid)'];
        const car = [r.year, r.make, r.model, r.submodel].filter(Boolean).join(' ');
        if (car) bits.push(car);
        if (r.ecuid) bits.push('ECUID ' + r.ecuid);
        if (r.memmodel) bits.push(r.memmodel);
        if (r.filesize) bits.push(r.filesize);
        return bits.join(' · ');
    }

    /* defs: array of RESOLVED definition objects (Defs.resolveBase output).
     * scalingBook: name -> scaling object (optional).
     * Returns { markdown, csv, stats } */
    function buildMap(defs, scalingBook) {
        const stats = { defs: 0, tablesAddressed: 0, tablesTotal: 0, checksumRows: 0 };
        const md = [];
        const csv = [['definition', 'ecuid', 'address', 'controls', 'layout', 'values_mean', 'category', 'axes']];
        md.push('# FanTom — Definition Address Map');
        md.push('');
        md.push('Every address below comes from a loaded XML definition. "Controls" is the');
        md.push('table\'s own name/description from that definition — what writing to the');
        md.push('address changes. Generated by FanTom defmap-export; no addresses guessed.');
        md.push('');

        const sorted = [...defs].sort((a, b) => defTitle(a).localeCompare(defTitle(b)));
        // index first
        md.push('## Index');
        md.push('');
        for (const def of sorted) {
            const addressed = (def.tables || []).filter(t => t.address != null || t.storageAddress != null);
            md.push('- ' + defTitle(def) + ' — ' + addressed.length + ' addressed table(s), ' +
                (def.tables || []).length + ' table(s) total');
        }
        md.push('');

        for (const def of sorted) {
            stats.defs++;
            const r = def.romid || {};
            md.push('## ' + defTitle(def));
            md.push('');
            const rows = [];
            for (const cs of (def.checksums || [])) {
                if (Number.isInteger(cs.sumloc)) { rows.push({ addr: cs.sumloc, name: 'Checksum SUM word', layout: 'uint32', mean: 'nisckfix recomputes this after any edit', cat: 'Checksum', axes: '' }); stats.checksumRows++; }
                if (Number.isInteger(cs.xorloc)) { rows.push({ addr: cs.xorloc, name: 'Checksum XOR word', layout: 'uint32', mean: 'nisckfix recomputes this after any edit', cat: 'Checksum', axes: '' }); stats.checksumRows++; }
            }
            for (const t of (def.tables || [])) {
                stats.tablesTotal++;
                const addr = t.address != null ? t.address : t.storageAddress;
                if (addr == null) continue;
                stats.tablesAddressed++;
                rows.push({
                    addr,
                    name: controlsText(t),
                    layout: layoutText(t),
                    mean: scalingText(t.scaling, scalingBook),
                    cat: (t.category || []).filter(Boolean).join(' / '),
                    axes: axisText(t),
                });
            }
            rows.sort((a, b) => a.addr - b.addr);
            if (!rows.length) {
                md.push('No tables with addresses in this definition (template or unmatched stub).');
                md.push('');
                continue;
            }
            md.push('| Address | Controls | Layout | Values mean | Category |');
            md.push('|---|---|---|---|---|');
            for (const row of rows) {
                const esc = (s) => String(s || '').replace(/\|/g, '\\|');
                md.push('| ' + hex(row.addr) + ' | ' + esc(row.name) + ' | ' + esc(row.layout) +
                    ' | ' + esc(row.mean) + ' | ' + esc(row.cat) + ' |');
                const q = (s) => '"' + String(s || '').replace(/"/g, '""') + '"';
                csv.push([r.xmlid || '', r.ecuid || '', hex(row.addr), row.name, row.layout, row.mean, row.cat, row.axes].map(q).join(','));
            }
            md.push('');
        }
        md.push('---');
        md.push('Totals: ' + stats.defs + ' definition(s), ' + stats.tablesAddressed +
            ' addressed table(s), ' + stats.checksumRows + ' checksum slot(s), ' +
            stats.tablesTotal + ' table(s) in total.');
        return { markdown: md.join('\n') + '\n', csv: csv.map(r => Array.isArray(r) ? r.join(',') : r).join('\n') + '\n', stats };
    }

    function harvestScalings(xmlText, book) {
        book = book || {};
        const re = /<scalingbase\b([^>]*)>/gi;
        let m;
        const attr = (txt, n) => {
            const mm = new RegExp(n + '\\s*=\\s*"([^"]*)"', 'i').exec(txt);
            return mm ? mm[1] : '';
        };
        while ((m = re.exec(xmlText))) {
            const name = attr(m[1], 'name');
            if (name) book[name] = {
                units: attr(m[1], 'units'),
                expression: attr(m[1], 'expression') || 'x',
                toByte: attr(m[1], 'to_byte') || 'x',
            };
        }
        return book;
    }

    const api = { buildMap, harvestScalings };

    if (typeof window !== 'undefined') {
        window.DefMapExport = api;
        // Browser glue: export every definition in the Defs registry.
        api.exportAll = function () {
            if (typeof Defs === 'undefined') throw new Error('definitions engine not loaded');
            const ids = Defs.list();
            if (!ids.length) throw new Error('no definitions loaded — load definitions first');
            const book = {};
            const defs = [];
            for (const id of ids) {
                const def = Defs.get(id);
                if (def.raw) harvestScalings(def.raw, book);
                defs.push(Defs.resolveBase(def));
            }
            // bases themselves may hold scalings their children reference
            const out = buildMap(defs, book);
            const blob = new Blob([out.markdown], { type: 'text/markdown' });
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = 'ADDRESS-MAP.md';
            document.body.appendChild(a);
            a.click();
            setTimeout(function () { URL.revokeObjectURL(a.href); a.remove(); }, 3000);
            return out.stats;
        };
    }
    if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
